name: nikah_plus
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_dash: ^1.0.0  
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo2.png
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/hands.png
    - assets/images/bg.png
    - assets/images/bg logo.png
    - assets/images/fb.png
    - assets/images/x.png
    - assets/images/apple.png
    - assets/images/hand2.png
    - assets/images/logo3.png
    - assets/images/border.png
    - assets/images/match1.png
    - assets/images/match2.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/bg content.png
    - assets/images/content.png
    - assets/images/ddd.png
    - assets/images/like.png
    - assets/images/sss.png
    - assets/images/box4.png
    - assets/images/box5.png
    - assets/images/box6.png
    - assets/images/box7.png
    - assets/images/content.png
    - assets/images/ddd.png
    - assets/images/like.png
    - assets/images/sss.png
    - assets/images/box4.png
    - assets/images/box5.png
    - assets/images/box6.png
    - assets/images/box7.png
    - assets/images/bg content.png
    - assets/images/bg1.png
    - assets/images/content.png
    - assets/images/heart1.png
    - assets/images/ddd.png
    - assets/images/like.png
    - assets/images/sss.png
    - assets/images/box4.png
    - assets/images/box5.png
    - assets/images/box6.png
    - assets/images/box7.png
    - assets/images/bg content.png
    - assets/images/bg2.png
    - assets/images/bg1.png
    - assets/images/ddd.png
    - assets/images/ddd.png
    - assets/images/like.png
    - assets/images/sss.png
    - assets/images/box4.png
    - assets/images/box5.png
    - assets/images/box6.png
    - assets/images/box7.png
    - assets/images/photos.png
    - assets/images/v1.png
    - assets/images/ibox.png
    - assets/images/card1.png
    - assets/images/card2.png
    - assets/images/card3.png
    - assets/images/card4.png
    - assets/images/card5.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/v2.png
    - assets/images/ibox1.png
    - assets/images/card6.png
    - assets/images/card7.png
    - assets/images/card8.png
    - assets/images/card9.png
    - assets/images/card10.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/Manage All.png
    - assets/images/card11.png
    - assets/images/card12.png
    - assets/images/card13.png
    - assets/images/card14.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/v3.png
    - assets/images/ibox3.png
    - assets/images/card15.png
    - assets/images/card16.png
    - assets/images/card17.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/input.png
    - assets/images/cardS.png
    - assets/images/card21.png
    - assets/images/card22.png
    - assets/images/card23.png
    - assets/images/card24.png
    - assets/images/card25.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/input.png
    - assets/images/cardS.png
    - assets/images/26.png
    - assets/images/27.png
    - assets/images/28.png
    - assets/images/29.png
    - assets/images/30.png
    - assets/images/31.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/input.png
    - assets/images/cardS.png
    - assets/images/card21.png
    - assets/images/card22.png
    - assets/images/card23.png
    - assets/images/card24.png
    - assets/images/card25.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/input.png
    - assets/images/cardS.png
    - assets/images/32.png
    - assets/images/33.png
    - assets/images/34.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/5.png
    - assets/images/6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/ficon.png
    - assets/images/fibox.png
    - assets/images/85.png
    - assets/images/78.png
    - assets/images/92.png
    - assets/images/88.png
    - assets/images/f1.png
    - assets/images/f2.png
    - assets/images/f3.png
    - assets/images/f4.png
    - assets/images/f5.png
    - assets/images/f6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/ficon.png
    - assets/images/fibox.png
    - assets/images/f7.png
    - assets/images/f8.png
    - assets/images/f9.png
    - assets/images/f10.png
    - assets/images/f11.png
    - assets/images/f12.png
    - assets/images/f13.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/ficon.png
    - assets/images/fibox.png
    - assets/images/r1.png
    - assets/images/r2.png
    - assets/images/r3.png
    - assets/images/f14.png
    - assets/images/f15.png
    - assets/images/f16.png
    - assets/images/f17.png
    - assets/images/f18.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/ficon.png
    - assets/images/fibox.png
    - assets/images/f19.png
    - assets/images/f20.png
    - assets/images/f21.png
    - assets/images/f22.png
    - assets/images/f23.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/icon.png
    - assets/images/mahr1.png
    - assets/images/mahr2.png
    - assets/images/mahr3.png
    - assets/images/mahr4.png
    - assets/images/edu.png
    - assets/images/fin.png
    - assets/images/cult.png
    - assets/images/age.png
    - assets/images/marital.png
    - assets/images/emp.png
    - assets/images/region.png
    - assets/images/info.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/icon1.png
    - assets/images/mahr5.png
    - assets/images/mahr6.png
    - assets/images/mahr7.png
    - assets/images/mahr8.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/icon4.png
    - assets/images/icon5.png
    - assets/images/icon6.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/micon.png
    - assets/images/step1.png
    - assets/images/step2.png
    - assets/images/step3.png
    - assets/images/step4.png
    - assets/images/icon7.png
    - assets/images/icon7.png
    - assets/images/icon7.png
    - assets/images/icon7.png
    - assets/images/icon7.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/eicon.png
    - assets/images/jimage1.png
    - assets/images/discovery.png
    - assets/images/jstep2.png
    - assets/images/jstep2b.png
    - assets/images/jstep3.png
    - assets/images/jstep4.png
    - assets/images/jstep4.png
    - assets/images/jstep4.png
    - assets/images/excitement.png
    - assets/images/patience.png
    - assets/images/thoughtfulness.png
    - assets/images/clarity.png
    - assets/images/journal.png
    - assets/images/box.png
    - assets/images/box1.png
    - assets/images/box2.png
    - assets/images/box3.png
    - assets/images/ibimage1.png
    - assets/images/ibimage2.png
    - assets/images/active1.png
    - assets/images/active2.png
    - assets/images/pending.png